### ISSUE TITLE
[Bug]: No available text to translate on Main Page

### ISSUE THREAD

**Issue by azazaazur** [streamyfin/streamyfin#667]
### What happened?

Mostly referring to "Continue Watching" and "Nextup" sections. I realized that they are not translated so I tried to look at them so I could translate it to Turkish but there aren't any on the en.json file"

### Reproduction steps

N/A

### Which device and operating system are you using?

N/A

### Version

0.28.0

### If applicable, please add screenshots to help explain your problem. You can drag and drop images here or paste them directly into the comment box.

![Image](https://github.com/user-attachments/assets/6cb30c93-5c38-4c9b-bccc-d238c35b3b4a)

Highlighted the text I am referring to.

**Comment by Ryan0204** [comment]
Should be fixed in develop branch. 

![Image](https://github.com/user-attachments/assets/f2a06c6b-3e6e-4f97-a1b0-c07b4dac1020)

**Comment by azazaazur** [comment]
Issue is still present on version 0.30.2 Reopening this issue.
