### ISSUE TITLE
[Bug]: Transcoding not working media with external ass subtitles

### ISSUE THREAD

**Issue by isZYKerman** [streamyfin/streamyfin#975]
### What happened?

I'm using v0.30.2 of Streamyfin but the "which version are you using" section in this page ends up at v0.29

------------------------------------------------------------------------

As the title described, transcoding is not working with external ass subtitles.

While downloading media with external ASS subtitles, the download won't start. It will remain "Downloading" for several minutes and ended up with an entry which is only 2-3MB and cannot be played. No logs were generated. However if I disable subtitles while downloading OR download without transcoding (the MAX option in the quality menu), the entry could be downloaded successfully.

While played directedly with transcoding on, the subtitle will not be displayed even enabled. However, when played directedly with transcoding off (the MAX option in the quality menu), the subtitle can be displayed correctly. No logs were generated.

Note that:
1. For other videos whose subtitle is in other codec, transcoding playback/download with subtitles enabled seems successful.
2. Using official client/webui to play these media with transcoding and subtitle on is successful.

### Reproduction steps

As shown above.

### Which device and operating system are you using?

Huawei Nova 11, HarmonyOS 4.2

### Version

0.29.0

### If applicable, please add screenshots to help explain your problem. You can drag and drop images here or paste them directly into the comment box.

No screenshots available.

**Comment by isZYKerman** [comment]
Well when I specific a bitrate while playing media with streamyfin, the console page in Jellyfin webui settings tells me that the playback is "direct" and no transcoding are performed. However the average network IO of my client device DOES change. Is that expected?

**Comment by Simon-Eklundh** [comment]
That sounds weird... If you set the bitrate to lower than the media bitrate it should transcode...

Been trying to replicate the main bug, but I can't find a single external ass

**Comment by isZYKerman** [comment]
I'll try to record my screen

**Comment by isZYKerman** [comment]
Github refuses to upload files bigger than 10MB🥲. Please view my screen recording [here](https://1drv.ms/v/c/859d8299703406b0/ESbcrMwfl5VMh8tOHeapoFoBzDAmt7br59PXnDI-V1d1fw). @Simon-Eklundh

**Comment by Simon-Eklundh** [comment]
Alright, so assuming I'm not forgetting anything:

1. We don't seem to report transcoding despite transcoding (I've verified this, but I would expect that to be an issue in jellyfin as I'm fairly certain we're using a transcoding URL)
2. Subtitles defaulting to wrong on transcoding (I've seen this reported elsewhere in relation to externals, subtitles are a mess (I know lostb1t made an issue regarding this today))
3. Subs not showing up on transcode. I'd wager there are two possible reasons for this a. A bug with external subs or b. Your subs are in Chinese (although the Japanese ones showed, right?....)

I've tried with embedded ass in English and those worked

**Comment by isZYKerman** [comment]
1. I don't know, to be honest. It's not a big deal after all, for it is only a display error. 

2. I don't quite understand what do you mean by "defaulting to wrong"... If you mean the part in which I chose Chinese sub but got Japanese sub displayed, I believe that it is because that the Chinese sub cannot be displayed and Streamyfin "falled back" to the Japanese sub for some reason.

3. Well it's hard to decide. The correctly displayed one was embedded PGSSUB. I don't have any English subs on my server.

Feel free to ask me for these videos so that you can test them.

**Comment by Simon-Eklundh** [comment]
1 true, it's weird tho

2. I meant the fallback which might also be a selection issue

3. very weird...

to make completely sure: when you talk about .ass external subs, you actually have a file with subtitles in the ass format?

if so: you can upload that sub file here :) https://palmr.oakgrove.site/r/GNO5yeegk4

otherwise, I have a lot of ASS (although not much in non-english tbh)

**Comment by isZYKerman** [comment]
I now tend to believe that this is because that the subs are in Chinese, because the embedded ass subtitle in Chinese (below, I think that it is embedded because that it's not flagged as "external" (外部)) has got the same issue.
![Screenshot_20250823_234626_edit_93544621251762.jpg](https://github.com/user-attachments/assets/9368b497-6c4a-4ce4-80e7-2177fd126c82)

**Comment by Simon-Eklundh** [comment]
That would make sense; i have seen that reported before.. Although back then it was Chinese being [] [][] instead of an actual character

Think it was a server issue then but I can't recall

**Comment by isZYKerman** [comment]
Well, yes, if you are talking about the webui player. This can be solved easily with a few settings in the server and many Chinese SNS networks have articles to tell you how to perform the settings (like [this one](https://post.smzdm.com/p/a5dro4d3/)). I have done those settings and my server is OK with subtitles and transcoding both on while using the webui.
![image](https://github.com/user-attachments/assets/0185dbf6-79a2-47db-bd2d-3801d490c3be)

Besides, your website always report error while uploading. I guess it's because that the connection between my laptop and your server is unstable. Please try to download the file from my server [(here)](https://nextcloud.zykerman.site/s/Cyn6XBtebEFDX9B).
![image](https://github.com/user-attachments/assets/5ab2fb6d-536e-4e77-9a7e-1ff888ba9083)

**Comment by Simon-Eklundh** [comment]
considering the size of the file, it could be a browser error... some browsers block files larger than 2gb iirc

2 hours download time is rough tho :D

**Comment by isZYKerman** [comment]
Is there anything interesting you have found?

**Comment by Simon-Eklundh** [comment]
Not really, but lostb1t thinks it's a bug with subtitle selection on transcoded which should be fixed now on develop (although ass will not look like ass)

**Comment by isZYKerman** [comment]
@Simon-Eklundh Well I tried 0.47.1 today and found that the issue is still there. 

1. During playback, with transcoding on, `ass` external substitutes were still not displayed.
2. Some episodes could be downloaded with both transcoding and subtitle on. They took up reasonable space but couldn't be played. The player remained in black screen, still responsive, but not playing anything. Some episodes just couldn't be doanloaded, with Streamyfin reporting errors seconds after I triggered the download.

**Comment by Simon-Eklundh** [comment]
I tried to replicate this

Found out I didn't seem to have any external .ass subs, and got busy with work and other stuff :/

Hopefully some other dev can replicate it

**Comment by oubaydos** [comment]
> 3. Subs not showing up on transcode. I'd wager there are two possible reasons for this a. A bug with external subs or b. Your subs are in Chinese (although the Japanese ones showed, right?....)

Hello, i have the same pb, no subtitles are shown when transcoding.
Version 0.54.1
